# General
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g default-terminal "tmux-256color"

# Plugins
set -g @plugin 'tmux-plugins/tpm' 
set -g @plugin 'tmux-plugins/tmux-sensible' 

# Theme customisation
set -g status-position bottom
set -g status-style "bg=default, fg=white"

set -g status-left "#[fg=green, bold] #S #[fg=default, nobold] "
set -g status-right "#[fg=white]%H:%M "

set -g window-status-format " #I:#W "
set -g window-status-current-style "fg=black, bg=white, bold"
set -g window-status-current-format " #I:#W "
